// Code generated by mockery v2.7.4. DO NOT EDIT.

package ethereum

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GraphQL is an autogenerated mock type for the GraphQL type
type GraphQL struct {
	mock.Mock
}

// Query provides a mock function with given fields: ctx, input
func (_m *GraphQL) Query(ctx context.Context, input string) (string, error) {
	ret := _m.Called(ctx, input)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
